DROP TABLE IF EXISTS USERS;
CREATE TABLE USERS (
  USERNAME VARCHAR(32) PRIMARY KEY,
  FULL_NAME VARCHAR(256) NOT NULL,
  EMAIL_ID EMAIL NOT NULL UNIQUE,
  PASSWORD_HASH VARCHAR(256) NOT NULL,
  DATE_OF_JOIN DATE DEFAULT CURRENT_DATE NOT NULL
);